# Generated by Django 5.2.11 on 2026-02-24 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donationrequest',
            unique_together={('donation', 'ngo')},
        ),
    ]
